// utils.h --- Various utility functions
// Copyright (C) 2006-2008 Wouter Boomsma
//
// This file is part of Phaistos
//
// Phaistos is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// Phaistos is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with Phaistos.  If not, see <http://www.gnu.org/licenses/>.


#ifndef RANDOM_H
#define RANDOM_H

#include <sstream>
#include <boost/random/mersenne_twister.hpp>
#include <boost/random/variate_generator.hpp>
#include <boost/random/uniform_real.hpp>
#include <boost/random/uniform_int.hpp>
#include <boost/random/normal_distribution.hpp>
#include "utils.h"

namespace phaistos {

//! Select random number engine
typedef boost::mt19937 RandomNumberEngine;

//! Global static generator
static RandomNumberEngine random_global(0u);

//! Set random number seed from string (assumes that string was generated by random_get_seed_string())
//!
//! \param random_number_engine Random number engine
//! \param str Input string containing seed
inline void random_set_seed_string(RandomNumberEngine &random_number_engine, std::string str) {
     std::string new_string = replace(str, ",", " " );
     std::istringstream stream;
     stream.str(new_string.c_str());
     stream >> random_number_engine;
}

//! Generate random number seed string 
//!
//! \param random_number_engine Random number engine
//! \return Seed string
inline std::string random_get_seed_string(RandomNumberEngine &random_number_engine) {
     return replace(strip(stringify(random_number_engine)), " ", ",");
}

}

#endif
